# Generated by Django 4.2.4 on 2023-08-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centermanagement",
            name="officials",
            field=models.ManyToManyField(blank=True, to="staff.centermanagement"),
        ),
    ]
