# Generated by Django 4.2.4 on 2023-08-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_centermanagement_officials'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='centermanagement',
            name='address',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centermanagement',
            name='fullname',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='centermanagement',
            name='working_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='centermanagement',
            name='social_medias',
            field=models.ManyToManyField(to='staff.socialmedia'),
        ),
    ]
