version: '3.9'

services:
  db:
    image: postgres:14.1-alpine
    container_name: "cyber-security"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
