# Generated by Django 4.2.4 on 2023-08-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="type",
            field=models.CharField(
                choices=[("question", "Question"), ("contact", "Contact")],
                default="question",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
