# Generated by Django 4.2.4 on 2023-08-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_message_type_alter_document_file_alter_document_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="tags",
            field=models.ManyToManyField(blank=True, to="common.tag"),
        ),
    ]
