# Generated by Django 4.2.4 on 2023-08-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_alter_message_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="common.tag"
            ),
        ),
    ]
